/* eslint-disable @next/next/no-img-element */
import Image from "next/image";
import ProgressBar from "react-bootstrap/ProgressBar";
import Head from "next/head";
import React from "react";
import { useEffect, useState } from "react";
import axios from "axios";
import CountDown from "../components/count";
import Router from "next/router";
import Link from "next/link";
import { Dropdown } from "react-bootstrap";
import cookiesHandler from "../helpers/cookies";
import { auth, login } from "../utils/auth";

const apiUrl = "http://localhost:8888/api";

export async function getServerSideProps(ctx) {
  const { token } = await auth(ctx);

  if (token) {
    ctx.res.writeHead(302, { Location: "/phase2" });
    ctx.res.end();
    return { props: {} };
  } else {
    return {
      props: {},
    };
  }
}

export default function Home() {
  const [activeEvent, setActiveEvent] = useState(null);
  const [currentProgress, setCurrentProgress] = useState(0);
  const [eventCapacity, setEventCapacity] = useState(0);
  const [currentUser, setCurrentUser] = useState(0);

  const [formRegister, setFormRegister] = useState({
    email: "",
    password: "",
    referral: "",
  });
  const [formLogin, setFormLogin] = useState({
    email: "",
    password: "",
  });

  // Fungsi untuk mendapatkan data event yang aktif
  const getActiveEvent = async () => {
    try {
      const response = await axios.get(`${apiUrl}/event/active`);
      if (!response?.data) return Router.reload();

      const getTicketByEventId = await axios.get(
        `${apiUrl}/ticket/by-event/${response.data.data.id}`
      );

      setActiveEvent(response.data.data);
      setEventCapacity(response.data.data.capacity);
      setCurrentProgress(
        (getTicketByEventId?.data?.data.count / response.data.data.capacity) *
          100
      );
      setCurrentUser(getTicketByEventId.data.data.count);

      // getTickets(response.data.data.id, response.data.data.capacity);
    } catch (error) {
      console.error(
        error?.response?.data.message ??
          error?.message ??
          "Failed to get active event"
      );
    }
  };

  // Fungsi untuk menghandle login
  const handleLogin = async (e) => {
    e.preventDefault();

    try {
      const response = await axios.post(
        `${apiUrl}/participant/login`,
        formLogin
      );

      if (response.status === 200 && response.data.status === "success") {
        const getDetail = await axios.get(`${apiUrl}/participant/getData`, {
          headers: {
            authorization: `Bearer ${response.data.data.token}`,
          },
        });

        cookiesHandler.setCookie(
          "user",
          JSON.stringify(getDetail.data.data),
          1
        );
        login(response.data.data.token);
      }
    } catch (error) {
      window.alert(
        error?.message ?? error?.response?.data.message ?? "Unknown error"
      );
    }
  };

  // Fungsi untuk mendaftar user baru
  const handleRegister = async (e) => {
    e.preventDefault();

    const registerData = {
      ...formRegister,
      name: "Participant",
    };

    if (!registerData.email || !registerData.password) {
      alert("Email and Password is required");
      return;
    }

    try {
      const response = await axios.post(
        `${apiUrl}/participant/register`,
        registerData
      );
      if (!response.data) return Router.reload();

      const createTicket = await axios.post(
        `${apiUrl}/ticket/${response.data.data.id}/${activeEvent.id}`
      );
      if (!createTicket.data) return Router.reload();

      window.alert("Register Success");
      getActiveEvent();
      return;
    } catch (error) {
      window.alert(
        error?.response?.data.message ?? error?.message ?? "Register Failed"
      );
    }
  };

  const handleOnChange = (target, event) => {
    const { name, value } = event.target;

    if (target === "login") {
      setFormLogin((prevState) => ({
        ...prevState,
        [name]: value,
      }));
    } else {
      setFormRegister((prevState) => ({
        ...prevState,
        [name]: value,
      }));
    }
  };

  useEffect(() => {
    getActiveEvent();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <Head>
        <title>Bisnis Indonesia ID</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="background">
        <header>
          <div className="container">
            <div className="row justify-content-end">
              <div className="col-md-4 col-6">
                <div className="text-center">
                  {getActiveEvent && getActiveEvent.logo ? (
                    <Image
                      src={`${apiUrl}/image/download/${getActiveEvent.logo}`}
                      alt=""
                      width={237.92}
                      height={50}
                    />
                  ) : (
                    <Image
                      src="/img/logo.png"
                      alt="Logo Bisnis Indonesia"
                      width={237.92}
                      height={50}
                    />
                  )}
                </div>
              </div>
              <div className="col-md-4 col-3">
                <div className="dropdown text-end">
                  <Dropdown>
                    <Dropdown.Toggle
                      id="dropdown-basic"
                      type="button"
                      className="btn btn-outline-light me-2 btn-light btn-sm px-3 fw-bold"
                      style={{ color: "#0b57a7" }}
                    >
                      LOG IN{" "}
                    </Dropdown.Toggle>
                    <Dropdown.Menu className="px-1" align="end">
                      <div className="mb-1">
                        <label
                          htmlFor="exampleFormControlInput1"
                          className="form-label"
                        >
                          Email address
                        </label>
                        <input
                          type="email"
                          name="email"
                          className="form-control"
                          id="exampleFormControlInput1"
                          placeholder="Enter email"
                          value={formLogin.email}
                          onChange={(e) => handleOnChange("login", e)}
                        />
                      </div>
                      <div className="mb-1">
                        <label
                          htmlFor="exampleFormControlInput1"
                          className="form-label"
                        >
                          Password
                        </label>
                        <input
                          type="password"
                          name="password"
                          className="form-control"
                          id="exampleFormControlInput1"
                          placeholder="Enter Password"
                          value={formLogin.password}
                          onChange={(e) => handleOnChange("login", e)}
                        />
                      </div>
                      <div className="d-grid gap-2 mt-2">
                        <button
                          className="btn btn-primary"
                          type="submit"
                          onClick={(e) => handleLogin(e)}
                        >
                          Login
                        </button>
                      </div>
                    </Dropdown.Menu>
                  </Dropdown>
                </div>
              </div>
            </div>
          </div>
        </header>

        <section className="register">
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-md-auto col-9">
                <p className="text-center">
                  Register your account and get a voucher 100k for a
                  Subscription Plan
                </p>
              </div>
            </div>
            <form
              className="row justify-content-center form-register"
              onSubmit={(e) => handleRegister(e)}
            >
              <div className="col-md-auto col-sm-auto col-10 mb-4">
                <input
                  onChange={(e) => handleOnChange("register", e)}
                  value={formRegister.email}
                  type="email"
                  className="form-control"
                  id="inputEmail"
                  name="email"
                  placeholder="Your Email"
                  required
                />
              </div>
              <div className="col-md-auto col-sm-auto col-10 mb-4">
                <input
                  onChange={(e) => handleOnChange("register", e)}
                  value={formRegister.password}
                  type="password"
                  className="form-control"
                  id="inputPassword"
                  name="password"
                  placeholder="Your Password"
                  required
                />
              </div>
              <div className="col-md-auto col-sm-auto col-10 mb-3">
                <input
                  onChange={(e) => handleOnChange("register", e)}
                  value={formRegister.referral}
                  type="referrer"
                  className="form-control"
                  id="referrerCode"
                  name="referral"
                  placeholder="Referral Code"
                />
              </div>
              <div className="col-md-auto col-sm-auto col-auto mb-3">
                <button type="submit" className="btn btn-create">
                  Create Account
                </button>
              </div>
            </form>
          </div>
        </section>

        <section className="event">
          <div className="container">
            <div className="row justify-content-center position-relative">
              <div className="col-md-auto col-sm-auto col-auto px-0">
                {activeEvent && activeEvent?.image1 ? (
                  <Image
                    className="rounded-first"
                    src={`${apiUrl}/image/download/${activeEvent?.image1}`}
                    alt=""
                    width={275}
                    height={260}
                  />
                ) : (
                  <Image
                    className="rounded-first"
                    src="/img/1.png"
                    alt=""
                    width={275}
                    height={260}
                  />
                )}
              </div>
              <div className="col-md-auto col-sm-auto col-auto px-0">
                {activeEvent && activeEvent?.image2 ? (
                  <Image
                    className="rounded-second"
                    src={`${apiUrl}/image/download/${activeEvent?.image2}`}
                    alt=""
                    width={275}
                    height={260}
                  />
                ) : (
                  <Image src="/img/2.png" alt="" width={275} height={260} />
                )}
              </div>
              <div className="col-md-auto col-sm-auto col-auto px-0">
                {activeEvent && activeEvent?.image3 ? (
                  <Image
                    className="rounded-third"
                    src={`${apiUrl}/image/download/${activeEvent?.image3}`}
                    alt=""
                    width={275}
                    height={260}
                  />
                ) : (
                  <Image
                    className="rounded-third"
                    src="/img/3.png"
                    alt=""
                    width={275}
                    height={260}
                  />
                )}
              </div>
              <div className="col-md-auto col-sm-auto col-auto px-0">
                {activeEvent && activeEvent?.image4 ? (
                  <Image
                    className="rounded-last"
                    src={`${apiUrl}/image/download/${activeEvent?.image4}`}
                    alt=""
                    width={275}
                    height={260}
                  />
                ) : (
                  <Image
                    className="rounded-last"
                    src="/img/4.png"
                    alt=""
                    width={275}
                    height={260}
                  />
                )}
              </div>
              <div className="d-flex justify-content-center">
                <p className="prog-info position-absolute top-50 start-50 translate-middle">
                  {currentUser} of {eventCapacity} users have participated in
                  this event
                </p>
                <div className="prog-bar col-md-11 col-8 position-absolute top-50 start-50 translate-middle">
                  {/* <ProgressBar variant={"YOU_PICK_A_NAME"} now={currentProgress} /> */}
                  <ProgressBar now={currentProgress} />
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="count">
          <CountDown time={activeEvent?.held ?? Date.now()} />
        </section>

        <section className="article">
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-md-auto col-9">
                <p className="text-center title">Articles you can read</p>
              </div>
            </div>
            <div className="row justify-content-center">
              <div className="col-md-4 col-10">
                <div className="row">
                  <div className="col-md-auto col-auto mb-3">
                    <img
                      src="/img/article1.png"
                      alt=""
                      width="77px"
                      height="64px"
                    />
                  </div>
                  <div className="col-md-8 col-8 px-0">
                    <h5>Economics</h5>
                    <p>
                      Which economics have done best and worst during the
                      pandemic?
                    </p>
                  </div>
                </div>
              </div>
              <div className="col-md-4 col-10">
                <div className="row">
                  <div className="col-md-auto col-auto mb-3">
                    <img
                      src="/img/article2.png"
                      alt=""
                      width="77px"
                      height="64px"
                    />
                  </div>
                  <div className="col-md-8 col-8 px-0">
                    <div className="d-flex flex-row">
                      <h5>Finance</h5>
                      <h4 className="bg-dark text-white ms-2">PREMIUM</h4>
                    </div>
                    <p>
                      Which economics have done best and worst during the
                      pandemic?
                    </p>
                  </div>
                </div>
              </div>
              <div className="col-md-4 col-10">
                <div className="row">
                  <div className="col-md-auto col-auto mb-3">
                    <img
                      src="/img/article3.png"
                      alt=""
                      width="77px"
                      height="64px"
                    />
                  </div>
                  <div className="col-md-8 col-8 px-0">
                    <div className="d-flex flex-row">
                      <h5>Industry</h5>
                      <h4 className="bg-dark text-white ms-2">PREMIUM</h4>
                    </div>
                    <p>
                      Which economics have done best and worst during the
                      pandemic?
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="package">
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-md-5 col-10 mb-3">
                <div className="bronze">
                  <div className="row">
                    <div className="col-md-3 col-auto position-relative py-1">
                      <img
                        src="./img/B Bronze.png"
                        className="ms-3"
                        alt=""
                        width="55px"
                        height="69px"
                      />
                      <h2 className="text-white position-absolute top-50 start-50 translate-middle ms-2">
                        Bronze
                      </h2>
                    </div>
                    <div className="col-md-4 col-auto ps-0">
                      <ul>
                        <li className="mt-3">Lorem ipsum dolor sit</li>
                        <li className="mt-2">Lorem ipsum dolor sit</li>
                      </ul>
                    </div>
                    <div className="col-md-4 col-auto pe-0">
                      <ul>
                        <li className="mt-3">Lorem ipsum dolor sit</li>
                        <li className="mt-2">Lorem ipsum dolor sit</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-md-5 col-10 mb-3">
                <div className="silver">
                  <div className="row">
                    <div className="col-md-3 col-auto position-relative py-1">
                      <img
                        src="./img/B Silver.png"
                        className="ms-3"
                        alt=""
                        width="55px"
                        height="69px"
                      />
                      <h2 className="text-white position-absolute top-50 start-50 translate-middle ms-1">
                        Silver
                      </h2>
                      {/* <br/><span className="text-white">Durasi 3 Bulan</span> */}
                    </div>
                    <div className="col-md-4 col-auto ps-0">
                      <ul>
                        <li className="mt-3">Lorem ipsum dolor sit</li>
                        <li className="mt-2">Lorem ipsum dolor sit</li>
                      </ul>
                    </div>
                    <div className="col-md-4 col-auto pe-0">
                      <ul>
                        <li className="mt-3">Lorem ipsum dolor sit</li>
                        <li className="mt-2">Lorem ipsum dolor sit</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-md-5 col-10 mb-3">
                <div className="gold">
                  <div className="row">
                    <div className="col-md-3 col-auto position-relative py-1">
                      <img
                        src="./img/B Gold.png"
                        className="ms-3"
                        alt=""
                        width="55px"
                        height="69px"
                      />
                      <h2 className="text-white position-absolute top-50 start-50 translate-middle ms-0">
                        Gold
                      </h2>
                    </div>
                    <div className="col-md-4 col-auto ps-0">
                      <ul>
                        <li className="mt-3">Lorem ipsum dolor sit</li>
                        <li className="mt-2">Lorem ipsum dolor sit</li>
                      </ul>
                    </div>
                    <div className="col-md-4 col-auto pe-0">
                      <ul>
                        <li className="mt-3">Lorem ipsum dolor sit</li>
                        <li className="mt-2">Lorem ipsum dolor sit</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-md-5 col-10 mb-3">
                <div className="platinum">
                  <div className="row">
                    <div className="col-md-3 col-auto position-relative py-1">
                      <img
                        src="./img/B Platinum.png"
                        className="ms-3"
                        alt=""
                        width="55px"
                        height="69px"
                      />
                      <h2 className="text-black position-absolute top-50 start-50 translate-middle ms-3">
                        Platinum
                      </h2>
                      {/* <br/><span>Durasi 12 Bulan</span> */}
                    </div>
                    <div className="col-md-4 col-auto ps-0">
                      <ul>
                        <li className="mt-3 text-black">
                          Lorem ipsum dolor sit
                        </li>
                        <li className="mt-2 text-black">
                          Lorem ipsum dolor sit
                        </li>
                      </ul>
                    </div>
                    <div className="col-md-4 col-auto pe-0">
                      <ul>
                        <li className="mt-3 text-black">
                          Lorem ipsum dolor sit
                        </li>
                        <li className="mt-2 text-black">
                          Lorem ipsum dolor sit
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <footer>
          <div className="container">
            <div className="d-flex flex-row justify-content-center">
              <div className="me-5 info">For more info</div>
              <div className="ms-0 d-flex align-items-center">
                <img
                  src="/img/vector.png"
                  alt=""
                  width="24px"
                  height="23.85px"
                />
              </div>
              <div className="ms-4 d-flex align-items-center">
                <img
                  src="/img/vector (1).png"
                  alt=""
                  width="24px"
                  height="19.51px"
                />
              </div>
              <div className="ms-4 d-flex align-items-center">
                <img
                  src="/img/vector (2).png"
                  alt=""
                  width="24px"
                  height="24px"
                />
              </div>
              <div className="ms-4 d-flex align-items-center">
                <img
                  src="/img/vector (3).png"
                  alt=""
                  width="24px"
                  height="24px"
                />
              </div>
              <div className="ms-4 d-flex align-items-center">
                <img
                  src="/img/vector (4).png"
                  alt=""
                  width="23.99px"
                  height="16.77px"
                />
              </div>
            </div>
            <div className="row justify-content-center mt-3">
              <Link href="/privacy-policy">
                <a className="col-md-auto col-auto">Privacy Policy</a>
              </Link>
            </div>
          </div>
        </footer>
      </div>
    </>
  );
}
