/* eslint-disable @next/next/no-img-element */
import Image from "next/image";
import ProgressBar from "react-bootstrap/ProgressBar";
import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";
import Router from "next/router";

export default function Phase1() {
  const [data, setData] = useState({});
  const [current, setCurrent] = useState(0);
  const [limit, setLimit] = useState(0);
  const [now, setNow] = useState(0);

  // variabel untuk mengambil data dari event yang aktif
  const getData = async () => {
    try {
      const result = await axios.get(`http://localhost:8888/api/event/active`);
      if (!result.data) {
        return Router.replace("/");
      }
      setData(result.data);
      const capacity = result.data.capacity;

      const nextResult = await axios.get(
        `http://localhost:8888/api/ticket/by-event/${result.data.id}`
      );

      setNow((nextResult.data.count / capacity) * 100); // progress bar
      setLimit(capacity); // kapasitas maksimal peserta event
      setCurrent(nextResult.data.count); // total peserta event yang terdaftar
    } catch (error) {}
  };

  useEffect(() => {
    getData();
  }, []);

  return (
    <>
      <Head>
        <title>Bisnis Indonesia ID</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="background">
        <header>
          <div className="container">
            <div className="row justify-content-end">
              <div className="col-md-4 col-6">
                {data && data.logo ? (
                  <img
                    className="mx-auto d-block"
                    src={`http://localhost:8888/api/image/download/${data.logo}`}
                    alt="Logo Bisnis Indonesia"
                    width="237.92px"
                    height="50px"
                  />
                ) : (
                  <img
                    className="mx-auto d-block"
                    src="/img/logo.png"
                    alt="Logo Bisnis Indonesia"
                    width="237.92px"
                    height="50px"
                  />
                )}
              </div>
              <div className="col-md-4 col-6">
                <div className="row justify-content-end">
                  <div className="col-md-auto me-4">
                    <img
                      src="./img/user.png"
                      className="mx-auto d-block"
                      alt=""
                      width="32"
                      height="32"
                    />
                    <a href="#" className="text-primary">
                      <p className="text-center mt-3">John Doe</p>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </header>

        <section className="event">
          <div className="container">
            <div className="row justify-content-center position-relative">
              <div className="col-md-auto col-sm-auto col-auto px-0">
                {data && data.image1 ? (
                  <img
                    className="rounded-first"
                    src={`http://localhost:8888/api/image/download/${data.image1}`}
                    alt=""
                    width="275px"
                    height="260px"
                  />
                ) : (
                  <img
                    className="rounded-first"
                    src="./img/1.png"
                    // style={{ backgroundImage:'rgba(11, 87, 167, 0.5);'}}
                    alt=""
                    width="275px"
                    height="260px"
                  />
                )}
              </div>
              <div className="col-md-auto col-sm-auto col-auto px-0">
                {data && data.image2 ? (
                  <img
                    src={`http://localhost:8888/api/image/download/${data.image2}`}
                    alt=""
                    width="275px"
                    height="260px"
                  />
                ) : (
                  <img src="./img/2.png" alt="" width="275px" height="260px" />
                )}
              </div>
              <div className="col-md-auto col-sm-auto col-auto px-0">
                {data && data.image3 ? (
                  <img
                    src={`http://localhost:8888/api/image/download/${data.image3}`}
                    alt=""
                    width="275px"
                    height="260px"
                  />
                ) : (
                  <img src="./img/3.png" alt="" width="275px" height="260px" />
                )}
              </div>
              <div className="col-md-auto col-sm-auto col-auto px-0">
                {data && data.image4 ? (
                  <img
                    className="rounded-last"
                    src={`http://localhost:8888/api/image/download/${data.image4}`}
                    alt=""
                    width="275px"
                    height="260px"
                  />
                ) : (
                  <img
                    className="rounded-last"
                    src="./img/4.png"
                    alt=""
                    width="275px"
                    height="260px"
                  />
                )}
              </div>
              <div className="d-flex justify-content-center">
                <p className="prog-info position-absolute top-50 start-50 translate-middle">
                  {current} of {limit} users have participated in this event
                </p>
                <div className="prog-bar col-md-11 col-8 position-absolute top-50 start-50 translate-middle">
                  <ProgressBar variant={"YOU_PICK_A_NAME"} now={now} />
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="my-progress mt-5 mb-5">
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-md-auto">
                <h4 className="text-center">My Progress</h4>
                <p className="text-center mt-4">
                  Complete your progress bar to get attractive offers such as
                  vouchers and promos during the event.
                </p>
              </div>
            </div>
            <div className="row justify-content-start progresss-container mt-5">
              <div className="progresss" id="progresss"></div>
              <div className="col-md-2 text-center">
                <Image src="/img/aa.png" alt="" width={100} height={100} />
              </div>
              <div className="col-md-2 ms-4 text-center">
                <Image src="/img/aaa.png" alt="" width={100} height={100} />
              </div>
              <div className="col-md-2 ms-4 text-center">
                <Image src="/img/aaaa.png" alt="" width={100} height={100} />
              </div>
              <div className="col-md-2 ms-4 text-center">
                <Image src="/img/aaaa.png" alt="" width={100} height={100} />
              </div>
              <div className="col-md-2 ms-4 text-center">
                <Image src="/img/aaaa.png" alt="" width={100} height={100} />
              </div>
              <div className="col-md-auto ms-4 my-auto">
                <Image src="/img/next.png" alt="" width={32} height={32} />
              </div>
            </div>
            <div className="row">
              <div className="col-md-2 text-center">
                <p className="text-progress mt-2">Account Registration</p>
              </div>
              <div className="col-md-2 ms-4 text-center">
                <p className="text-progress-1 mt-2">Get 10% off</p>
              </div>
              <div className="col-md-2 ms-4 text-center">
                <p className="text-progress-2 mt-2">Get ...</p>
              </div>
              <div className="col-md-2 ms-4 text-center">
                <p className="text-progress-2 mt-2">Voucher XYZ30</p>
              </div>
              <div className="col-md-2 ms-4 text-center">
                <p className="text-progress-2 mt-2">Voucher XYZ30</p>
              </div>
            </div>
          </div>
        </section>

        <section className="article">
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-md-auto col-9">
                <p className="text-center title">Articles you can read</p>
              </div>
            </div>
            <div className="row justify-content-center">
              <div className="col-md-4 col-10">
                <div className="row">
                  <div className="col-md-auto col-auto mb-3">
                    <img
                      src="/img/article1.png"
                      alt=""
                      width="77px"
                      height="64px"
                    />
                  </div>
                  <div className="col-md-8 col-8 px-0">
                    <h5>Economics</h5>
                    <p>
                      Which economics have done best and worst during the
                      pandemic?
                    </p>
                  </div>
                </div>
              </div>
              <div className="col-md-4 col-10">
                <div className="row">
                  <div className="col-md-auto col-auto mb-3">
                    <img
                      src="/img/article2.png"
                      alt=""
                      width="77px"
                      height="64px"
                    />
                  </div>
                  <div className="col-md-8 col-8 px-0">
                    <div className="d-flex flex-row">
                      <h5>Finance</h5>
                      <h4 className="bg-dark text-white ms-2">PREMIUM</h4>
                    </div>
                    <p>
                      Which economics have done best and worst during the
                      pandemic?
                    </p>
                  </div>
                </div>
              </div>
              <div className="col-md-4 col-10">
                <div className="row">
                  <div className="col-md-auto col-auto mb-3">
                    <img
                      src="/img/article3.png"
                      alt=""
                      width="77px"
                      height="64px"
                    />
                  </div>
                  <div className="col-md-8 col-8 px-0">
                    <div className="d-flex flex-row">
                      <h5>Industry</h5>
                      <h4 className="bg-dark text-white ms-2">PREMIUM</h4>
                    </div>
                    <p>
                      Which economics have done best and worst during the
                      pandemic?
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="package">
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-md-5 col-10 mb-3">
                <div className="bronze">
                  <div className="row">
                    <div className="col-md-3 col-auto position-relative py-1">
                      <img
                        src="./img/B Bronze.png"
                        className="ms-3"
                        alt=""
                        width="55px"
                        height="69px"
                      />
                      <h2 className="text-white position-absolute top-50 start-50 translate-middle ms-2">
                        Bronze
                      </h2>
                    </div>
                    <div className="col-md-4 col-auto ps-0">
                      <ul>
                        <li className="mt-3">Lorem ipsum dolor sit</li>
                        <li className="mt-2">Lorem ipsum dolor sit</li>
                      </ul>
                    </div>
                    <div className="col-md-4 col-auto pe-0">
                      <ul>
                        <li className="mt-3">Lorem ipsum dolor sit</li>
                        <li className="mt-2">Lorem ipsum dolor sit</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-md-5 col-10 mb-3">
                <div className="silver">
                  <div className="row">
                    <div className="col-md-3 col-auto position-relative py-1">
                      <img
                        src="./img/B Silver.png"
                        className="ms-3"
                        alt=""
                        width="55px"
                        height="69px"
                      />
                      <h2 className="text-white position-absolute top-50 start-50 translate-middle ms-1">
                        Silver
                      </h2>
                      {/* <br/><span className="text-white">Durasi 3 Bulan</span> */}
                    </div>
                    <div className="col-md-4 col-auto ps-0">
                      <ul>
                        <li className="mt-3">Lorem ipsum dolor sit</li>
                        <li className="mt-2">Lorem ipsum dolor sit</li>
                      </ul>
                    </div>
                    <div className="col-md-4 col-auto pe-0">
                      <ul>
                        <li className="mt-3">Lorem ipsum dolor sit</li>
                        <li className="mt-2">Lorem ipsum dolor sit</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-md-5 col-10 mb-3">
                <div className="gold">
                  <div className="row">
                    <div className="col-md-3 col-auto position-relative py-1">
                      <img
                        src="./img/B Gold.png"
                        className="ms-3"
                        alt=""
                        width="55px"
                        height="69px"
                      />
                      <h2 className="text-white position-absolute top-50 start-50 translate-middle ms-0">
                        Gold
                      </h2>
                    </div>
                    <div className="col-md-4 col-auto ps-0">
                      <ul>
                        <li className="mt-3">Lorem ipsum dolor sit</li>
                        <li className="mt-2">Lorem ipsum dolor sit</li>
                      </ul>
                    </div>
                    <div className="col-md-4 col-auto pe-0">
                      <ul>
                        <li className="mt-3">Lorem ipsum dolor sit</li>
                        <li className="mt-2">Lorem ipsum dolor sit</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-md-5 col-10 mb-3">
                <div className="platinum">
                  <div className="row">
                    <div className="col-md-3 col-auto position-relative py-1">
                      <img
                        src="./img/B Platinum.png"
                        className="ms-3"
                        alt=""
                        width="55px"
                        height="69px"
                      />
                      <h2 className="text-black position-absolute top-50 start-50 translate-middle ms-3">
                        Platinum
                      </h2>
                      {/* <br/><span>Durasi 12 Bulan</span> */}
                    </div>
                    <div className="col-md-4 col-auto ps-0">
                      <ul>
                        <li className="mt-3 text-black">
                          Lorem ipsum dolor sit
                        </li>
                        <li className="mt-2 text-black">
                          Lorem ipsum dolor sit
                        </li>
                      </ul>
                    </div>
                    <div className="col-md-4 col-auto pe-0">
                      <ul>
                        <li className="mt-3 text-black">
                          Lorem ipsum dolor sit
                        </li>
                        <li className="mt-2 text-black">
                          Lorem ipsum dolor sit
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <footer>
          <div className="container">
            <div className="d-flex flex-row justify-content-center">
              <div className="me-5 info">For more info</div>
              <div className="ms-0 d-flex align-items-center">
                <img
                  src="/img/vector.png"
                  alt=""
                  width="24px"
                  height="23.85px"
                />
              </div>
              <div className="ms-4 d-flex align-items-center">
                <img
                  src="/img/vector (1).png"
                  alt=""
                  width="24px"
                  height="19.51px"
                />
              </div>
              <div className="ms-4 d-flex align-items-center">
                <img
                  src="/img/vector (2).png"
                  alt=""
                  width="24px"
                  height="24px"
                />
              </div>
              <div className="ms-4 d-flex align-items-center">
                <img
                  src="/img/vector (3).png"
                  alt=""
                  width="24px"
                  height="24px"
                />
              </div>
              <div className="ms-4 d-flex align-items-center">
                <img
                  src="/img/vector (4).png"
                  alt=""
                  width="23.99px"
                  height="16.77px"
                />
              </div>
            </div>
          </div>
        </footer>
      </div>
    </>
  );
}
