/* eslint-disable @next/next/link-passhref */
/* eslint-disable @next/next/no-img-element */
import Image from "next/image";
import Head from "next/head";
import Link from "next/link";

export default function Policy() {
  return (
    <>
      <Head>
        <title>Bisnis Indonesia ID | Privacy Policy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-md-auto col-6">
              <Link href="/">
                <Image
                  src="/img/logo.png"
                  alt="Logo Bisnis Indonesia"
                  width={237.92}
                  height={50}
                />
              </Link>
            </div>
          </div>
        </div>
      </header>

      <section className="policy">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-md-9">
              <h3>Syarat &amp; Ketentuan</h3>
              <p>
                Selamat datang di DataIndonesia.id. Sebelum Anda melakukan
                pendaftaran DataIndonesia.id, silakan membaca Syarat dan
                Ketentuan di bawah ini.
              </p>
              <p>
                Selama menggunakan DataIndonesia.id maka Anda setuju untuk
                terikat dan mematuhi syarat dan ketentuan yang berlaku. Kami
                dapat mengubah syarat dan ketentuan setiap saat, dengan atau
                tanpa pemberitahuan sebelumnya dan pengguna setuju untuk
                mematuhi syarat dan ketentuan tersebut.
              </p>
              <ol>
                <li>
                  Mengenai penggunaan username:
                  <ul type="disc">
                    <li>
                      Dilarang menggunakan username yang mengandung pelecehan
                      terhadap SARA, pornografi, brand/merek atau nama lainnya
                      yang dilindungi oleh hak cipta.
                    </li>
                    <li>
                      Selama menggunakan username DataIndonesia.id Anda terikat
                      oleh syarat &amp; ketentuan yang berlaku khusus di kanal
                      yang bersangkutan maupun syarat &amp; ketentuan secara
                      umum.
                    </li>
                    <li>
                      Kami berhak untuk dapat menghentikan atau men-suspend akun
                      dan/atau penggunaan Anda untuk jangka waktu sementara
                      ataupun seterusnya, dengan atau tanpa pemberitahuan
                      terlebih dahulu.
                    </li>
                    <li>
                      Kami berhak untuk dapat menghentikan akun atau penggunaan
                      Anda pada situs kami apabila akun Anda melanggar syarat
                      dan ketentuan yang sudah tertera tanpa harus
                      memberitahukan alasan tersebut.
                    </li>
                    <li>
                      Poin yang telah terkumpul pada akun yang dihentikan karena
                      melanggar syarat dan ketentuan yang berlaku tidak bisa
                      dialihkan kepada akun lainnya.
                    </li>
                    <li>
                      Kami tidak bertanggung jawab kepada Anda ataupun pihak
                      lainnya atas penghentian akun atau penggunaan yang telah
                      dihentikan dari situs kami.
                    </li>
                  </ul>
                </li>

                <li className="mt-3">
                  Situs kami, termasuk didalamnya konten text, foto, gambar,
                  video dan audio, dilindungi oleh hak cipta dan kami memiliki
                  segala hak atas hal konten tersebut sesuai dengan perjanjian
                  yang dilakukan sebelumnya jika ada.
                </li>

                <li className="mt-3">
                  Dengan mengirimkan konten pada website pengguna telah
                  memberikan hak pada kami dan pihak-pihak yang bekerja sama
                  dengan kami untuk menerbitkan atau mempublikasikan atau
                  meng-copy konten tersebut pada website kami dan untuk
                  keperluan promosi.
                </li>

                <li className="mt-3">
                  Pengguna akan sepenuhnya bertanggung jawab atas konten yang
                  telah dikirimkan kepada kami dan telah dipublikasikan melalui
                  website kami ataupun pihak-pihak yang bekerja sama dengan
                  kami.
                </li>

                <li className="mt-3">
                  DataIndonesia.Id menggunakan layanan pihak ketiga untuk
                  mengoptimalkan pengalaman pengguna, misalnya MidTrans untuk
                  metode pembayaran. Saat menggunakan layanan DataIndonesia.id
                  Anda mungkin akan diminta untuk mengidentifikasi diri Anda
                  agar DataIndonesia.id dapat mengoptimalkan layanan untuk Anda.
                  Misalnya menyediakan informasi pilihan Anda, mengirimkan
                  notifikasi topik-topik, isu-isu, kegiatan atau peristiwa yang
                  mungkin Anda tertarik, dan tidak tertutup kemungkinan untuk
                  membatasi akses konten dewasa. Untuk autentifikasi
                  identifikasi diri, Anda dapat menggunakan layanan pengelolaan
                  identitas atau akun pihak ke-tiga.
                </li>

                <li className="mt-3">
                  Deskripsi lengkap mengenai DataIndonesia.id
                  <ul type="disc">
                    <p className="fw-bold mb-1">
                      Pernyataan tentang control security yang digunakan untuk
                      melindungi customer
                    </p>
                    <li className="mt-0">
                      Password akun
                      <ul type="circle">
                        <li>
                          Untuk keamanan akun, Pengguna harus menjaga
                          kerahasiaan akun, tidak membuat password yang mudah
                          ditebak, dan mengubah password secara berkala
                        </li>
                        <li>
                          BisnisindonesiaID tidak memiliki akses terhadap
                          password pengguna dan tidak akan meminta password
                          pengguna untuk alasan apapun
                        </li>
                        <li>
                          Jika lupa password, bisa pakai fitur forgot password
                          dimana link untuk reset password akan dikirim ke email
                          user
                        </li>
                      </ul>
                    </li>
                  </ul>
                </li>

                <li className="mt-3">
                  Mengenai penggunaan konten kami:<br></br>Dilarang untuk
                  menyalin, menggandakan, mereproduksi ulang, menerbitkan ulang
                  mengunggah ulang, mendistribusikan, mempublikasikan, menyimpan
                  ke dalam database, menampilkan, memodifikasi, membuat karya
                  turunan dari dan/atau dengan cara apapun memanfaatkan setiap
                  bagian dari situs kami kecuali mendapatkan izin secara
                  explisit dan tertulis dari kami. Semua Konten di dalam
                  DataIndonesia.id merupakan hak milik DataIndonesia.id dan
                  dilindungi oleh Undang-Undang Hak Cipta.
                </li>

                <li className="mt-3">
                  Segala sesuatu informasi tentang profil pengguna yang
                  diberikan kepada kami akan kami jaga kerahasiaannya dan tidak
                  akan dipublikasikan kepada pihak ketiga manapun, kecuali
                  dengan persetujuan pengguna yang akan ditanyakan sebelumnya.
                </li>

                <li className="mt-3">
                  Anda setuju bahwa apabila kami mendapatkan surat perintah
                  pengadilan yang dikeluarkan oleh pengadilan atau penegak hukum
                  Negara Indonesia, kami harus memenuhi dan bekerja sama dengan
                  pihak tersebut dan memberikan informasi mengenai Anda termasuk
                  data profil atau informasi lainnya yang telah diberikan kepada
                  kami tanpa memerlukan persetujuan dari pengguna.
                </li>

                <li className="mt-3">
                  Anda berhak untuk melindungi hak pribadi Anda dengan
                  menghubungi kami melalui email, surat atau telepon yang dapat
                  ditemukan di situs kami.
                </li>

                <li className="mt-3">
                  Anda setuju untuk bertanggung jawab dan membebaskan kami dan
                  pihak-pihak yang bekerja sama dengan kami atas setiap kerugian
                  yang kami terima dari pelanggaran yang Anda lakukan terhadap
                  syarat dan ketentuan yang berlaku.
                </li>

                <li className="mt-3">
                  Penggunaan Data Pribadi
                  <p className="mb-0">
                    Anda dengan ini setuju bahwa Data Pribadi akan kami olah
                    dalam rangka:
                  </p>
                  <ul type="disc">
                    <li>
                      memberikan akses bagi Anda ke Layanan Kami dan memastikan
                      bahwa Konten dan Layanan ditampilkan dengan cara yang
                      paling efektif untuk Anda;
                    </li>
                    <li>
                      memberikan kepada Anda informasi terkait Konten Situs,
                      Produk, Layanan dan Layanan Interaktif yang Anda minta
                      dari kami;
                    </li>
                    <li>untuk memproses keanggotaan Anda;</li>
                    <li>
                      melaksanakan kewajiban Kami yang timbul dari setiap
                      perjanjian yang diadakan antara Anda dan Kami;
                    </li>
                    <li>
                      pengembangan Layanan Kami, termasuk namun tidak terbatas
                      pada pemecahan masalah, analisis data, pengujian,
                      penelitian, tujuan statistik serta survei;
                    </li>
                    <li>
                      untuk membuat analisa statistik dalam rangka pengembangan
                      produk Kami;
                    </li>
                    <li>
                      membuat keputusan terkait dengan pembukaan atau kelanjutan
                      terhadap aktifnya Username Anda serta pembuatan,
                      penyediaan atau kelanjutan dari Layanan dan juga untuk
                      menjaga akurasi Data Pribadi;
                    </li>
                    <li>
                      menyediakan informasi dan Data Pribadi yang relevan
                      tentang Anda kepada pihak ketiga untuk tujuan memproses
                      keanggotaan dan/atau pengajuan peristiwa;
                    </li>
                    <li>
                      menilai atau memahami efektivitas iklan kami dan iklan
                      pihak ketiga pada Aplikasi Kami dan pada website pihak
                      ketiga lain, dan untuk menyampaikan iklan yang relevan
                      kepada Anda;
                    </li>
                    <li>
                      memberitahu Anda tentang perubahan-perubahan terhadap
                      layanan kami;
                    </li>
                    <li>
                      memenuhi persyaratan-persyaratan hukum yang berlaku pada
                      DataIndonesia.id dan Bisnis Indonesia berdasarkan
                      peraturan perundang-undangan yang berlaku;
                    </li>
                    <li>
                      mengelola hubungan antara DataIndonesia.id dengan Anda,
                      termasuk menyediakan informasi kepada Anda tentang
                      Layanan, sepanjang diizinkan berdasarkan syarat dan
                      ketentuan ini serta peraturan perundang-undangan yang
                      berlaku; dan
                    </li>
                    <li>
                      untuk memasarkan produk yang terkait dengan Layanan
                      melalui berbagai metode komunikasi termasuk surat,
                      telepon, SMS, faksimili, email, internet, riset pasar, dan
                      merancang atau menyaring produk atau layanan yang serupa
                      termasuk dengan melakukan riset pasar, analisis data, dan
                      survei;
                    </li>
                  </ul>
                  <p className="mt-2">
                    Anda dengan ini setuju bahwa Kami dapat menggunakan Data
                    Pribadi untuk tujuan lain yang berkaitan dengan hal-hal
                    sebagaimana disebutkan dalam butir 12, sesuai dengan
                    peraturan perundang-undangan yang berlaku.
                  </p>
                  <p>
                    Anda dengan ini setuju bahwa Kami dapat berbagi Data Pribadi
                    dengan pihak-pihak berikut sepanjang tidak bertentangan
                    dengan peraturan perundang-undangan yang berlaku:
                  </p>
                  <ul type="disc">
                    <li>
                      para mitra usaha, untuk pelaksanaan setiap perjanjian yang
                      kami adakan dengan mereka atau Anda;
                    </li>
                    <li>
                      para pengiklan dan jaringan-jaringan iklan yang memerlukan
                      data dalam memilih iklan yang relevan kepada Anda dan
                      orang lain. Kami tidak mengungkapkan informasi terkait
                      individu yang dapat diidentifikasi kepada para pengiklan,
                      tetapi kami dapat memberikan mereka informasi terkait
                      agregat tentang Para Pengguna kami (sebagai contoh, kami
                      dapat memberitahu mereka bahwa 125 orang pria berusia di
                      bawah 33 tahun mengakses iklan mereka pada periode
                      tertentu). Kami juga dapat menggunakan informasi agregat
                      tersebut untuk membantu para pengiklan dalam rangka
                      menjangkau jenis audiens yang mereka ingin targetkan. Kami
                      dapat menggunakan informasi atau data yang dikumpulkan
                      dari Anda untuk memungkinkan kami memenuhi keinginan para
                      pengiklan kami dengan menampilkan iklan mereka kepada
                      audiens yang menjadi target dari iklan tersebut;
                    </li>
                    <li>
                      penyedia analisis dan mesin pencari yang membantu kami
                      dalam peningkatan dan optimalisasi situs kami;
                    </li>
                    <li>
                      calon penjual atau pembeli bisnis atau aset apabila kami
                      menjual atau membeli bisnis atau aset apapun, dalam hal
                      ini kami dapat mengalihkan Data Pribadi Anda kepada
                      pembeli atau penjual tersebut sebagai bagian dari
                      transaksi;
                    </li>
                    <li>
                      setiap organisasi ataupun perorangan, jika kami memiliki
                      kewajiban untuk mengungkapkan Data Pribadi Anda guna
                      mematuhi setiap kewajiban hukum, atau untuk melaksanakan
                      dan menerapkan Syarat Dan Ketentuan Kami, Kebijakan Cookie
                      kami, dan ketentuan lainnya, atau untuk melindungi hak,
                      aset, atau keamanan dari DataIndonesia.id dan Bisnis
                      Indonesia serta pihak-pihak terafiliasinya, Para Pengguna
                      atau lainnya. Ini termasuk pertukaran informasi dengan
                      perusahaan dan organisasi lain untuk tujuan perlindungan
                      dari penipuan dan antisipasi termasuk dan tidak terbatas
                      terhadap risiko kredit;
                    </li>
                    <li>
                      agen, kontraktor atau penyedia layanan pihak ketiga yang
                      menyediakan administrasi, pengiriman pos, telemarketing,
                      telekomunikasi penjualan langsung, call center, proses
                      bisnis, perjalanan, visa, manajemen pengetahuan, sumber
                      daya manusia, pengolahan data, teknologi informasi,
                      komputer, pembayaran, penagihan utang, referensi kredit
                      atau pemeriksaan-pemeriksaan latar belakang lain atau
                      layanan-layanan lain kepada DataIndonesia.id atau Bisnis
                      Indonesia atau pihak terafiliasinya;
                    </li>
                    <li>
                      lembaga keuangan yang mana terhadap badan tersebut, Anda
                      memiliki atau mengajukan untuk memiliki urusan terkait
                      dengan setiap Produk dan/atau Layanan;
                    </li>
                    <li>
                      orang atau entitas yang kepada orang atau entitas
                      tersebut, DataIndonesia.id atau pihak terafiliasinya
                      berkewajiban untuk melakukan pengungkapan sesuai dengan
                      proses hukum atau berdasarkan persyaratan hukum,
                      peraturan, perintah pengadilan, yang mengikat atau berlaku
                      untuk DataIndonesia.id atau Pihak Terafiliasinya (afiliasi
                      langsung maupun tidak langsung) dan terhadap otoritas
                      pemerintah, atau setiap pengungkapan berdasarkan dan untuk
                      tujuan pedoman atau petunjuk yang diberikan atau
                      dikeluarkan oleh badan penegak hukum, regulasi, badan
                      pemerintah, otoritas pajak, lembaga penegak hukum atau
                      lembaga otoritas-otoritas lain, atau peraturan otonom dari
                      badan industri atau asosiasi dari penyedia jasa keuangan
                      yang disyaratkan untuk dipenuhi oleh DataIndonesia.ia atau
                      Bisnis Indonesia atau pihak terafiliasinya, atau setiap
                      pengungkapan sesuai dengan setiap komitmen dari
                      DataIndonesia.id atau Bisnis Indonesia atau pihak
                      terafiliasinya dengan lembaga hukum, regulasi, badan
                      pemerintah, pajak, lembaga penegak hukum atau
                      otoritas-otoritas lain, atau badan otonom atau industri
                      atau asosiasi dari penyedia jasa keuangan, atau bursa
                      efek, termasuk pengungkapan ke sidang pengadilan,
                      pengadilan tribunal, dan/atau lembaga hukum, regulasi,
                      pajak dan badan pemerintah, terlepas apakah proses hukum,
                      kewajiban, permintaan, persyaratan, atau pedoman tersebut
                      saat ini masih ada atau dibuat di masa mendatang;
                    </li>
                    <li>
                      lembaga keuangan, agen proses, atau pihak lainnya yang
                      terlibat; dan
                    </li>
                    <li>
                      penerima pengalihan yang sebenarnya atau yang diajukan
                      dari DataIndonesia.id atau pihak terafiliasinya, atau
                      peserta atau sub-peserta atau penerima pengalihan hak-hak
                      DataIndonesia.id atau pihak terafiliasinya sehubungan
                      dengan Anda, dan semua atau sebagian dari aset atau bisnis
                      dari DataIndonesia.id atau Bisnis Indonesia atau pihak
                      terafiliasinya.
                    </li>
                  </ul>
                </li>

                <li className="mt-3">
                  Kerahasiaan Kata Sandi<br></br>Kata sandi atau password,
                  termasuk kata sandi Username merupakan tanggung jawab personal
                  Anda masing-masing. DataIndonesia.id atau Bisnis Indonesia
                  atau pihak terafiliasinya tidak bertanggung jawab atas
                  kerugian yang dapat ditimbulkan akibat kelalaian pengguna
                  dalam menjaga kerahasiaan kata sandi atau password-nya.
                </li>

                <li className="mt-3">
                  Tautan Terhadap Platform Lainnya<br></br>Jika Anda mengikuti
                  salah satu tautan web yang terdapat pada platform ini, harap
                  diingat bahwa web tersebut memiliki kebijakan syarat dan
                  ketentuan tersendiri dan kami tidak mengemban tanggung jawab
                  dalam bentuk apapun atas ketentuan-ketentuan maupun
                  jaminan-jaminan yang terdapat dalam syarat dan ketentuan pada
                  web tersebut.
                </li>

                <li className="mt-3">
                  Cookies<br></br>Cookies adalah file berukuran kecil yang
                  secara otomatis akan mengambil tempat di dalam perangkat
                  komputer Anda, yang berguna untuk mengidentifikasi dan
                  memantau koneksi jaringan Anda sehingga Anda akan dapat
                  mengakses Layanan Kami secara lebih optimal. Cookies akan
                  membantu kami untuk menelusuri fitur yang paling menarik untuk
                  Anda dan jenis konten yang pernah Anda kunjungi di waktu lalu.
                  Saat Anda mengunjungi Aplikasi ini kembali, cookies akan
                  mempermudah untuk menyesuaikan konten sesuai dengan kebutuhan
                  Anda. Cookies tidak melakukan pelacakan terhadap informasi
                  pengguna secara individual, dan semua data cookies kami telah
                  terenkripsi dan tidak dapat dibaca oleh Aplikasi lain.
                  <br></br>
                  Walaupun secara setelan semula (default) perangkat komputer
                  Anda menerima cookies, Anda bebas untuk melakukan perubahan
                  terhadap setelan tersebut melalui pengaturan/setting browser
                  Anda, dengan memilih untuk menolak mengaktifkan cookies.
                </li>

                <li className="mt-3">
                  Akses Media Sosial<br></br>Dalam rangka pengembangan Layanan,
                  Anda memberikan kami izin dalam mengakses akun media sosial,
                  yang dalam hal ini termasuk namun tidak terbatas pada Twitter,
                  Facebook, Path, Google+ dan/atau LinkedIn.<br></br>Apabila
                  Anda memberikan Kami akses ke data akun media sosial Anda,
                  Anda setuju bahwa Kami hanya menggunakan data tersebut untuk
                  keperluan pelaksanaan Layanan DataIndonesia.id.
                </li>

                <li className="mt-3">
                  Keamanan Data Pribadi<br></br>Setiap Data Pribadi yang Kami
                  peroleh sesuai dengan ketentuan Kebijakan Privasi ini akan
                  dilindungi dengan upaya terbaik Kami melalui perangkat
                  keamanan teruji. Meskipun demikian, Kami tidak menjamin
                  kerahasiaan informasi yang Anda sampaikan tersebut, dalam
                  keadaan dimana terdapat pihak-pihak lain yang mengambil dan
                  memanfaatkan Data Pribadi tersebut dari Kami secara melawan
                  hukum. Kami akan berupaya sebaik mungkin untuk menghalangi
                  akses ke dalam Data Pribadi oleh pihak yang tidak berwenang.
                </li>

                <li className="mt-3">
                  Kewajiban Pembukaan Data Pribadi<br></br>Kami dapat diwajibkan
                  oleh peraturan-perundang-undangan yang berlaku untuk membuka
                  Data Pribadi dan informasi terkait Anda lainnya kepada pihak
                  ketiga yang berwenang seperti lembaga pemerintah, lembaga
                  kepolisian dan lembaga pengadilan hanya jika ada surat
                  perintah yang sah dari lembaga-lembaga tersebut.
                </li>

                <li className="mt-3">
                  Penolakan untuk Tujuan Pemasaran<br></br>Anda berhak untuk
                  meminta kami agar tidak memanfaatkan Data Pribadi Anda untuk
                  tujuan pemasaran. Kami akan memberitahu Anda dan meminta
                  persetujuan dari Anda sebelum Kami menggunakan Data Pribadi
                  Anda untuk tujuan tersebut atau jika kami bermaksud
                  mengungkapkan Data Pribadi Anda kepada pihak ketiga manapun
                  untuk tujuan tersebut. Anda dapat menggunakan hak Anda untuk
                  menolak pengolahan tersebut dengan cara memberikan tAnda pada
                  formulir yang terkait yang kami gunakan untuk mengumpulkan
                  data Anda. Bahkan setelah Anda memberikan persetujuan Anda
                  atas Data Pribadi yang akan digunakan untuk tujuan pemasaran,
                  Anda dapat, setiap saat setelah itu, menarik persetujuan Anda
                  dengan menghubungi kami sbb:
                  <p className="fw-bold mt-2">Alamat:</p>
                  <p className="bg-warning d-inline-flex">
                    Wisma Bisnis Indonesia, 5 Floor
                  </p>
                  <br></br>
                  <p className="bg-warning d-inline-flex">
                    Jl. KH Mas Mansyur No. 12A,
                  </p>
                  <br></br>
                  <p className="bg-warning d-inline-flex">
                    Karet Tengsin, Tanah Abang,
                  </p>
                  <br></br>
                  <p className="bg-warning d-inline-flex">
                    Jakarta Pusat 10220,
                  </p>
                  <br></br>
                  <p className="bg-warning d-inline-flex">Indonesia</p>
                  <br></br>
                  <p className="bg-warning d-inline-flex">
                    Telp: 021-57901023 ext 542
                  </p>
                  <br></br>
                  <p className="bg-warning d-inline-flex">
                    Email: cs@bisnisindonesia.id
                  </p>
                  <br></br>
                  <p className="bg-warning d-inline-flex">
                    Jam pelayanan: Senin-Jumat / 08.00-17.00 WIB
                  </p>
                </li>

                <li className="mt-3">
                  Perubahan Syarat dan Ketentuan Dari Waktu ke Waktu<br></br>
                  Syarat dan ketentuan ini dapat diubah dan/atau diperbaharui
                  dari waktu ke waktu oleh DataIndonesia.id DataIndonesia.id
                  mengimbau agar Anda membaca secara seksama dan memeriksa
                  halaman Syarat dan Ketentuan ini dari waktu ke waktu untuk
                  mengetahui perubahan apapun yang dapat terjadi. Dengan tetap
                  mengakses dan menggunakan Layanan DataIndonesia.id, maka
                  pengguna menyetujui dan terikat terhadap perubahan-perubahan
                  yang ada di dalam Syarat dan Ketentuan ini.
                </li>
              </ol>
            </div>
          </div>
        </div>
      </section>

      <footer>
        <div className="container">
          <div className="d-flex flex-row justify-content-center">
            <div className="me-5 info">For more info</div>
            <div className="ms-0 d-flex align-items-center">
              <img src="/img/vector.png" alt="" width="24px" height="23.85px" />
            </div>
            <div className="ms-4 d-flex align-items-center">
              <img
                src="/img/vector (1).png"
                alt=""
                width="24px"
                height="19.51px"
              />
            </div>
            <div className="ms-4 d-flex align-items-center">
              <img
                src="/img/vector (2).png"
                alt=""
                width="24px"
                height="24px"
              />
            </div>
            <div className="ms-4 d-flex align-items-center">
              <img
                src="/img/vector (3).png"
                alt=""
                width="24px"
                height="24px"
              />
            </div>
            <div className="ms-4 d-flex align-items-center">
              <img
                src="/img/vector (4).png"
                alt=""
                width="23.99px"
                height="16.77px"
              />
            </div>
          </div>
        </div>
      </footer>
    </>
  );
}
